### ISSUE TITLE
Doesn't Stack

### ISSUE THREAD

**Issue by OFWModz** [xKiraiChan/KiraiLib#1]

**Comment by OFWModz** [comment]
https://github.com/OFWModz/PlagueButtonAPI IT doesn't stack up fam

**Comment by xKiraiChan** [comment]
not enough details to continue this issue.

**Comment by Dayoftheplay** [comment]
lol

**Comment by TheRealShieri** [comment]
Imagine self advo their own api while its dog shit and your detection methods for you mods are as useful as trump in the Whitehouse.

**Comment by TheRealShieri** [comment]
@OFWModz Imagine self advo their own api while its dog shit and your detection methods for you mods are as useful as trump in the Whitehouse. Only way you detect crashers is by the word within avatars so how effective was that now?

**Comment by OFWModz** [comment]
I don't just check for the word. If you think that, you are extremely deluded. I check animations, avi name, particle systems, everything.

Soon a huge upgrade to the particle systems check will come.

**Comment by xKiraiChan** [comment]
@OFWModz do you check for scripts on avatars?

**Comment by OFWModz** [comment]
You mean the whitelisted ones that are actually loaded?

**Comment by xKiraiChan** [comment]
no, custom ones that can fry GPUs

**Comment by xSypherr** [comment]
> I don't just check for the word. If you think that, you are extremely deluded. I check animations, avi name, particle systems, everything.
> 
> Soon a huge upgrade to the particle systems check will come.

It's funny, since we tested your shit client a few days ago, literally any crasher I used worked.
You don't even know how to check for gO's 🤦

**Comment by OFWModz** [comment]
I literally dump hierarchy's fam, but lol k
Imagine thinking non whitelisted scripts load 🤔

**Comment by xSypherr** [comment]
> I literally dump hierarchy's fam, but lol k
> Imagine thinking non whitelisted scripts load 🤔

keep logging your users zzz all delusionals anyways

**Comment by xKiraiChan** [comment]
Imagine not realizing someone in this thread has SYSTEM_SCRIPTING_ACCESS and is literally a game dev

**Comment by OFWModz** [comment]
And who's that? 😂

**Comment by xKiraiChan** [comment]
@OFWModz you gotta switch to ML 3.0 for build 1046
astro is trying to tell you this
