### ISSUE TITLE
Can use XRef scan for InputPopup

### ISSUE THREAD

**Issue by affectioned** [xKiraiChan/KiraiLib#2]
I've noticed on your latest commit, that you have manually update input method that il2cpp compiler changes slightly name of. So I've thought about suggesting this. 
https://github.com/abbeybabbey/VRChatXrefScans/blob/66e809f283585be12c7da8e6d3d8e5251836bab5/VRChatXrefScans/XrefScanning/XrefScans/VRCUiPopupManagerMethods.cs#L14 as shown here, seems like it didn't break so far in any update and I keep the repo up to date

**Comment by xKiraiChan** [comment]
I used to use an XRef until the 1040 update broke it (I think), I don't play the game anymore so I made a quick patch to get this running again but never remade the XRef.

Although it would be good practice and would lower the chances of breaking between updates this repository is no longer used in any real capacity.
The only projects that rely on it are owned by me and are being rewritten. 

When I can confirm with other developers that this repository is no longer in use, I will archive it fully. Until then Ill keep it working with 0 effort patch commits
